services:
  3xui:
    image: ghcr.io/xeefei/3x-ui:latest
    container_name: 3xui_app
    # hostname: yourhostname <- optional
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
      - $PWD/wwwroot:/app/wwwroot
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_ENABLE_FAIL2BAN: "true"
    tty: true
    privileged: true  # 添加特权模式
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    # network_mode: host
    # 使用host网络模式时不需要显式映射端口
    # 如果使用非host模式，则需要取消下面的注释来映射端口
    ports:
      # - "80:80"
      - "2053:2053"
    restart: unless-stopped
  
  nginx:
    image: nginx:alpine
    container_name: 3xui_nginx
    volumes:
      - $PWD/wwwroot:/usr/share/nginx/html
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    restart: unless-stopped
